-- Optional starter directory. Verify handles before applying. No creator identities or reviews.
begin;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Nykaa','nykaa','nykaabeauty','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('boAt','boat','boat.nirvana','Tech','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Mamaearth','mamaearth','mamaearth.in','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('The Souled Store','the-souled-store','thesouledstore','Fashion','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Dot & Key','dot-key','dotandkey.skincare','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Myntra','myntra','myntra','Fashion','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Sugar Cosmetics','sugar-cosmetics','trysugar','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Minimalist','minimalist','beminimalist','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Plum','plum','plumgoodness','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Foxtale','foxtale','foxtaleskin','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Pilgrim','pilgrim','discover.pilgrim','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('mCaffeine','mcaffeine','mcaffeineofficial','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('WOW Skin Science','wow-skin-science','wowskinscienceindia','Beauty','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Zomato','zomato','zomato','Food & drink','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Swiggy','swiggy','swiggyindia','Food & drink','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Licious','licious','licious_foods','Food & drink','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Blue Tokai','blue-tokai','bluetokaicoffee','Food & drink','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Sleepy Owl','sleepy-owl','sleepyowlcoffee','Food & drink','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Paper Boat','paper-boat','paperboatdrinks','Food & drink','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Amul','amul','amul_india','Food & drink','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Lenskart','lenskart','lenskart','Fashion','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Fabindia','fabindia','fabindiaofficial','Fashion','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Bewakoof','bewakoof','bewakoofofficial','Fashion','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Snitch','snitch','snitch.co.in','Fashion','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Rare Rabbit','rare-rabbit','houseofrarerabbit','Fashion','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Noise','noise','go_noise','Tech','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('OnePlus India','oneplus-india','oneplus_india','Tech','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Croma','croma','croma.retail','Tech','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Samsung India','samsung-india','samsungindia','Tech','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Ather Energy','ather-energy','atherenergy','Lifestyle','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('IKEA India','ikea-india','ikea.india','Lifestyle','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Urban Company','urban-company','urbancompany','Lifestyle','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Wakefit','wakefit','wakefitco','Lifestyle','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Cult.fit','cult-fit','cultfitofficial','Fitness','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('MuscleBlaze','muscleblaze','muscleblaze','Fitness','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Boldfit','boldfit','boldfit.in','Fitness','brand',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('The Good Glamm Group','the-good-glamm-group','goodglammgroup','Agency','agency',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Winkl','winkl','winklapp','Agency','agency',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Chtrbox','chtrbox','chtrbox','Agency','agency',null,'active') on conflict do nothing;
insert into private.companies(name,slug,instagram_handle,category,entity_type,website,status) values('Qoruz','qoruz','qoruz','Agency','agency',null,'active') on conflict do nothing;
commit;
