const { test } = require('node:test');
const assert = require('node:assert/strict');
const { PGlite } = require('@electric-sql/pglite');
const fs = require('node:fs');
const path = require('node:path');

test('database authorization and product lifecycle', async () => {
  const db = new PGlite();
  try {
    await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth;
      create table auth.users(id uuid primary key, email_confirmed_at timestamptz);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
      create schema storage;
      create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
      alter table storage.objects enable row level security;
      grant usage on schema storage to authenticated;
      grant select,insert,update,delete on storage.objects to authenticated;`);
    for (const file of fs.readdirSync(path.join(__dirname,'../supabase/migrations')).sort())
      await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations',file),'utf8'));
    const ids = Array.from({length:8}, (_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`);
    const as = async (id, role='authenticated') => { await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id || '']); await db.exec(`set role ${role}`); };
    const rpc = async (name, arg) => (await db.query(`select public.${name}(${arg===undefined?'':'$1::jsonb'}) as value`,arg===undefined?[]:[JSON.stringify(arg)])).rows[0].value;
    for (const id of ids) await db.query('insert into auth.users values($1,now())',[id]);
    await as(null,'anon');
    assert.equal(await rpc('kollab_session'),null);
    await assert.rejects(()=>db.query('select * from private.instagram_verifications'),/permission denied/);
    await assert.rejects(()=>rpc('kollab_admin_queue'),/permission denied/);
    await assert.rejects(()=>rpc('kollab_expired_proofs'),/permission denied/);
    await as(ids[0]);
    assert.equal((await rpc('kollab_session')).verified,false);
    await assert.rejects(()=>rpc('kollab_admin_queue'),/Moderator access/);
    await assert.rejects(()=>rpc('kollab_update_profile',{alias:'Test',follower_band:'10k_25k',category:'Beauty',city:null,role:'admin'}));
    const challenge=await rpc('kollab_verification',{action:'start',handle:'test.creator'});
    assert.equal(challenge.status,'pending');
    await as(ids[1]);
    await rpc('kollab_session');
    await assert.rejects(()=>rpc('kollab_verification',{action:'submit',challenge_id:challenge.id}),/unavailable/);
    await as(ids[0]);
    await rpc('kollab_verification',{action:'submit',challenge_id:challenge.id});
    await db.exec('reset role');
    await db.query("insert into private.user_roles(user_id,role) values($1,'admin')",[ids[1]]);
    await as(ids[1]);
    await rpc('kollab_admin_action',{action:'verification',target_id:challenge.id,decision:'approved',reason:'Bio code checked manually'});
    const selfChallenge=await rpc('kollab_verification',{action:'start',handle:'moderator.test'});
    await rpc('kollab_verification',{action:'submit',challenge_id:selfChallenge.id});
    await assert.rejects(()=>rpc('kollab_admin_action',{action:'verification',target_id:selfChallenge.id,decision:'approved',reason:'Trying to approve myself'}),/Another moderator/);
    await as(ids[0]);
    assert.equal((await rpc('kollab_session')).verified,true);
    const company=await rpc('kollab_create_brand',{name:'Test Studio',instagram_handle:'teststudio',category:'Beauty',entity_type:'brand',website:null});
    assert.equal(company.status,'pending_review');
    await as(null,'anon');
    assert.deepEqual(await rpc('kollab_search_brands'),[]);
    await as(ids[1]);
    await rpc('kollab_admin_action',{action:'company',target_id:company.id,decision:'active',reason:'Checked company identity'});
    await as(ids[0]);
    const fixture=require('../data/reviews.json')[0];
    const fields=['collab_month','deal_type','cash_amount_inr','product_claimed_value_inr','product_actual_value_inr','deliverables','initial_offer_inr','final_amount_inr','payment_status','days_to_payment','ghost_stage','usage_rights_requested','usage_rights_paid_separately','ran_as_paid_ad_without_payment','revisions_requested','scope_creep','had_written_agreement','rating_communication','rating_professionalism','rating_payment','would_work_again','body'];
    const input=Object.fromEntries(fields.map(k=>[k,fixture[k]]));
    Object.assign(input,{brand_id:company.id,agency_id:null,collab_month:'2026-01',identity_mode:'anonymous',attribution_consent:false});
    await assert.rejects(()=>rpc('kollab_create_review',{...input,user_id:ids[1]}));
    const review=await rpc('kollab_create_review',input);
    assert.equal(review.visibility,'pending_review');
    assert.equal(review.attribution_handle,null);
    for(const key of ['user_id','created_at','storage_path','handle','city']) assert.equal(key in review,false,key);
    await assert.rejects(()=>rpc('kollab_create_review',{...input,collab_month:'2026-02',identity_mode:'attributed',attribution_consent:false}));
    const attributed=await rpc('kollab_create_review',{...input,collab_month:'2026-02',identity_mode:'attributed',attribution_consent:true});
    assert.equal(attributed.attribution_handle,'test.creator');
    await as(null,'anon');
    assert.deepEqual(await rpc('kollab_list_reviews'),[]);
    await as(ids[1]);
    for(const r of [review,attributed]) await rpc('kollab_admin_action',{action:'review',target_id:r.id,decision:'published',reason:'Reviewed for publication'});
    await as(null,'anon');
    const publicRows=await rpc('kollab_list_reviews');
    assert.equal(publicRows.length,1);
    assert.deepEqual(await db.query('select * from storage.objects').catch(()=>[]),[]);
    await as(ids[0]);
    const post=await rpc('kollab_create_post',{category:'Beauty',body:'How do usage rights work?',identity_mode:'anonymous',attribution_consent:false});
    assert.equal(post.visibility,'pending_review');
    await as(ids[1]);
    await rpc('kollab_admin_action',{action:'post',target_id:post.id,decision:'published',reason:'Useful community question'});
    await as(ids[0]);
    assert.equal((await rpc('kollab_list_posts')).length,1);
    const proof=await rpc('kollab_proof_reserve',{review_id:review.id,proof_type:'dm_screenshot',mime_type:'image/jpeg',byte_size:10});
    await db.query("insert into storage.objects(bucket_id,name,metadata) values('review-proofs',$1,$2)",[proof.path,{mimetype:'image/jpeg',size:10}]);
    await db.query('select public.kollab_proof_finalize($1)',[proof.id]);
    assert.equal((await db.query('select * from storage.objects')).rows.length,0,'creator cannot download evidence');
    await as(ids[2]);
    await rpc('kollab_session');
    await assert.rejects(()=>db.query('select public.kollab_proof_access($1)',[proof.id]));
    await assert.rejects(()=>db.query("insert into storage.objects(bucket_id,name,metadata) values('review-proofs',$1,'{}')",[proof.path]));
    await as(ids[1]);
    assert.equal((await db.query('select * from storage.objects')).rows.length,0,'moderator needs audited access');
    await db.query('select public.kollab_proof_access($1)',[proof.id]);
    assert.equal((await db.query('select * from storage.objects')).rows.length,1);
    await as(ids[0]);
    assert.deepEqual(await rpc('kollab_rates',{}),[],'small rate cells suppressed');
    // Five different verified creators, not five submissions by one creator.
    await rpc('kollab_update_profile',{alias:'Creator One',follower_band:'10k_25k',category:'Beauty',city:null});
    for(const id of ids.slice(2,7)) {
      await as(id); await rpc('kollab_session');
      await rpc('kollab_update_profile',{alias:'Test Creator',follower_band:'10k_25k',category:'Beauty',city:null});
      await db.exec('reset role');
      await db.query("insert into private.instagram_verifications(user_id,handle,method) values($1,$2,'manual_bio')",[id,'creator'+id.slice(-2)]);
      await as(id);
      const contribution=await rpc('kollab_create_review',{...input,final_amount_inr:18000});
      await as(ids[1]);
      await rpc('kollab_admin_action',{action:'review',target_id:contribution.id,decision:'published',reason:'Reviewed for rate test'});
    }
    await rpc('kollab_admin_action',{action:'refresh_rates',reason:'Release privacy protected rate cohorts'});
    await as(ids[0]);
    const rates=await rpc('kollab_rates',{});
    assert.equal(rates.length,1); assert.equal(rates[0].count,5); assert.equal(rates[0].median,18000);
    assert.equal(rates[0].min,null);assert.equal(rates[0].max,null);
    assert.deepEqual(await rpc('kollab_rates',{city:'Mumbai'}),[]);
    await as(null,'anon');
    assert.equal((await rpc('kollab_list_reviews')).length,1);
    const locked=await db.query('select public.kollab_list_reviews($1,$2) as rows',[company.id,{year:'2025'}]);
    assert.equal(locked.rows[0].rows.length,0,'filter cannot pick a new set of reviews');
    await as(ids[1]);
    await rpc('kollab_admin_action',{action:'ban',target_id:ids[2],decision:'banned',reason:'Ban invalidates rate contributions'});
    await as(ids[2]);
    await assert.rejects(()=>rpc('kollab_session'),/suspended|banned|unavailable/i);
    await as(ids[0]);
    assert.deepEqual(await rpc('kollab_rates',{}),[],'ban invalidates affected rate snapshot immediately');
    await as(ids[7]); await rpc('kollab_session');
    const claim=await rpc('kollab_claim_brand',{company_id:company.id,evidence:'Contact our independently listed company address to verify authority.'});
    assert.deepEqual((await db.query('select public.kollab_representative_reviews($1) as value',[company.id])).rows[0].value,[]);
    await assert.rejects(()=>rpc('kollab_reply',{review_id:review.id,body:'Thank you for your feedback.'}),/representation/);
    await as(ids[1]);
    await rpc('kollab_admin_action',{action:'claim',target_id:claim.id,decision:'approved',reason:'Verified company contact independently'});
    await as(ids[7]);
    assert.ok((await db.query('select public.kollab_representative_reviews($1) as value',[company.id])).rows[0].value.length>3);
    const reply=await rpc('kollab_reply',{review_id:review.id,body:'Thank you for your feedback.'});
    assert.equal(reply.visibility,'pending_review');
    await as(ids[1]);
    await rpc('kollab_admin_action',{action:'reply',target_id:reply.id,decision:'published',reason:'Response respects creator anonymity'});
    await rpc('kollab_admin_action',{action:'claim',target_id:claim.id,decision:'revoked',reason:'Representation no longer valid'});
    await as(ids[0]);
    assert.ok((await rpc('kollab_list_reviews')).every(r=>r.reply===null),'revoking a claim hides official replies');
    await assert.rejects(()=>rpc('kollab_expired_proofs'),/permission denied/);
    await db.exec('reset role');
    await db.query("update private.review_proofs set delete_after=now()-interval '1 day' where id=$1",[proof.id]);
    await as(null,'service_role');
    assert.equal((await rpc('kollab_expired_proofs')).length,1);
    await db.query('select public.kollab_expired_proofs_deleted($1)',[[proof.id]]);
    assert.deepEqual(await rpc('kollab_expired_proofs'),[]);
    await db.exec('reset role');
    const insecure=await db.query("select tablename from pg_tables t join pg_class c on c.relname=t.tablename join pg_namespace n on n.oid=c.relnamespace and n.nspname=t.schemaname where schemaname='private' and not c.relrowsecurity");
    assert.equal(insecure.rows.length,0);
    const exposed=await db.query("select tablename from pg_tables where schemaname='private' and (has_table_privilege('anon',quote_ident(schemaname)||'.'||quote_ident(tablename),'SELECT,INSERT,UPDATE,DELETE') or has_table_privilege('authenticated',quote_ident(schemaname)||'.'||quote_ident(tablename),'SELECT,INSERT,UPDATE,DELETE'))");
    assert.equal(exposed.rows.length,0,'no client table grants');
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/seed.sql'),'utf8'));
    assert.equal(Number((await db.query('select count(*) n from private.companies')).rows[0].n),41);
  } finally { await db.close(); }
});
